### PR TITLE
Landing Page Updates

### PR DESCRIPTION
**Pull request by colinfrederickson**
- Updates landing pages on all workflows to the document created during space creation.

### CODE REVIEW

**Comment by colinfrederickson** [comment]
@johnmosesman - had one question on this one!  there are notes on the dynamic and embedded workflows about documents:

`      // IMPORTANT NOTE: The document created below does not effect change in the embedded workflow. This is a copy of the document layout.
      // To change the document in the embedded workflow, you must set the document in the HCM.Show application within the props of useSpace.`

how would we wan to approach those updates to ensure that the landing page is the documented created during space creation?

**Comment by johnmosesman** [comment]
@colinfrederickson I believe for the embed/dynamic the document has to be supplied at runtime, for example here's the embedded one - https://github.com/FlatFilers/HCMShow/blob/main/components/embedded-portal/document.ts

I think we could cut the document here, and leave a note about it being dynamically supplied in the HCM app? Creating it here and it not doing anything is confusing I think.

**Comment by colinfrederickson** [comment]
@johnmosesman - that sounds good to me. If the document is supplied at runtime, like in that example, are we able to get the ID when it is created and use that as a the landing page?

**Comment by johnmosesman** [comment]
@colinfrederickson Landing page meaning set it as the first thing they see?

**Comment by colinfrederickson** [comment]
@johnmosesman - Exactly. this is new-ish functionality that was recently rolled out

**Review by johnmosesman — APPROVED** [review]
lgtm

**Pull request merged**
